const subjectRedirectLinks = {
  // All branches
  "BT-101": "https://career-shiksha.com/post/rgpv-question-papers-bt-101-engineering-chemistry/",
  "BT-102": "https://career-shiksha.com/post/rgpv-previous-year-question-paper-bt-102-mathematics-i/",
  "BT-103": "https://career-shiksha.com/post/rgpv-previous-year-question-papers-bt-103-english-for-communication//",
  "BT-104": "https://career-shiksha.com/post/rgpv-previous-year-question-papers-bt-104-basic-electrical-electronics-engineering/",
  "BT-105": "https://career-shiksha.com/post/rgpv-previous-year-question-papers-bt-105-engineering-graphics/",

  "BT-201": "https://career-shiksha.com/post/rgpv-question-papers-bt-201-engineering-physics/",
  "BT-202": "https://career-shiksha.com/post/rgpv-previous-year-question-paper-bt-202-mathematics-ii/",
  "BT-203": "https://career-shiksha.com/post/rgpv-previous-year-question-paper-bt-203-basic-mechanical-engineering-bme/",
  "BT-204": "https://career-shiksha.com/post/rgpv-previous-year-question-paper-bt-204-basic-civil-engineering-and-engineering-mechanics/",
  "BT-205": "https://career-shiksha.com/post/rgpv-previous-year-question-paper-bt-205-basic-computer-engineering/",
  
  //Computer Science and Engineering 
  "BT-301": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-bt-301-mathematics-iii-m-iii-b-tech/",
  "ES-301": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-es-301-energy-environment-engineering-b-tech/",
  "CS-302": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-302-discrete-structure-b-tech/",
  "CS-303": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-303-data-structures-b-tech/",
  "CS-304": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-304-digital-systems-b-tech/",
  "CS-305": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-305-object-oriented-programming-and-methodology-oopm-b-tech/",

  "BT-401": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-bt-401-mathematics-iii-b-tech/",
  "CS-402": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-402-analysis-design-of-algorithm-b-tech/",
  "CS-403": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-403-software-engineering-b-tech/",
  "CS-404": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-404-computer-organization-architecture-b-tech/",
  "CS-405": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-405-operating-systems-b-tech/",

  "CS-501": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-501-theory-of-computation-b-tech/",
  "CS-502": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-502-database-management-systems-b-tech/",
  "CS-503-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-503-a-data-analytics-b-tech/",
  "CS-503-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-503-c-cyber-security-b-tech/",
  "CS-504-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-504-a-internet-and-web-technology-b-tech/",
  "CS-504-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-504-b-object-oriented-programming-b-tech/",
  "CS-504-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-504-c-introduction-to-database-management-systems-b-tech/",

  "CS-601": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-601-machine-learning-b-tech/",
  "CS-602": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-602-computer-networks-b-tech/",  
  "CS-603-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-603-a-advanced-computer-architecture-b-tech/",
  "CS-603-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-603-c-compiler-design-b-tech/",
  "CS-604-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-604-b-project-management-b-tech/",
  
  "CS-701": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-701-software-architectures-b-tech/",
  "CS-702-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-702-c-wireless-mobile-computing-b-tech/",
  "CS-702-D": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-702-d-big-data-b-tech/",
  "CS-703-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-703-a-cryptography-and-information-security-b-tech/",
  "CS-703-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-703-b-data-mining-and-warehousing-b-tech/",

  "CS-801": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-801-internet-of-things-b-tech/",
  "CS-802-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-802-b-cloud-computing-b-tech/",
  "CS-803-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-803-a-image-processing-and-computer-vision-b-tech/",
  "CS-803-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-cs-803-c-internet-of-things-b-tech/",

  // Electrical and communication Engineering / ECE
  "BT-301": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-bt-301-mathematics-iii-m-iii-b-tech/",
  "EC-302": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-302-electronic-measurements-and-instrumentation-b-tech/",
  "EC-303": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-303-digital-system-design-b-tech/",
  "EC-304": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-304-electronic-devices-b-tech/",
  "EC-305": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-305-network-analysis-b-tech/",
  "ES-401": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-es-401-energy-environmental-engineering-b-tech/",
  "EC-402": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-402-signal-and-system-b-tech/",
  "EC-403": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-403-electronic-circuit-analysis-b-tech/",
  "EC-404": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-404-control-system-b-tech/",
  "EC-405": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-405-analog-circuit-b-tech/",
  "EC-501": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-501-microprocessor-and-its-application-b-tech/",
  "EC-502": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-502-digital-communication-b-tech/",
  "EC-503-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-503-b-mobile-communication-b-tech/",
  "EC-504-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-504-b-computer-system-organisation-b-tech/",
  "EC-601": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-601-digital-signal-processing-b-tech/",
  "EC-602": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-602-antenna-and-wave-propagation-b-tech/",
  "EC-603-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-603-a-data-communication-b-tech/",
  "EC-603-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-603-c-satellite-communication-b-tech/",
  "EC-604-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-604-c-power-electronics-b-tech/",
  "EC-701": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-701-vlsi-design-b-tech/",
  "EC-702-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-702-a-microwave-engineering-b-tech/",
  "EC-703-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-703-a-cellular-mobile-communication-b-tech/",
  "EC-703-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-703-b-internet-of-things-b-tech/",
  "EC-703-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-703-c-probability-theory-stochastic-processor-b-tech/",
  "EC-801": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-801-optical-fibre-communication-b-tech/",
  "EC-802-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-802-b-wireless-communication-b-tech/",
  "EC-803-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-803-a-wireless-network-b-tech/",

  // Mechanical Engineering ME
  "BT-301": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-bt-301-mathematics-iii-m-iii-b-tech/",
  "ME-302": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-302-engineering-thermodynamics-b-tech/",
  "ME-303": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-303-materials-technology-b-tech/",
  "ME-304": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-304-strength-of-material-b-tech/",
  "ME-305": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-305-manufacturing-processes-b-tech/",
  "ES-401": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-es-401-energy-environmental-engineering-b-tech/",
  "ME-402": "https://career-shiksha.com/post/rgpv-previous-year-question-paper-me-402-instrumentation-control/",
  "ME-403": "https://career-shiksha.com/post/rgpv-previous-year-question-paper-me-403-theory-of-machine-b-tech/",
  "ME-404": "https://career-shiksha.com/post/rgpv-previous-year-question-paper-me-404-fluid-mechanics-b-tech/",
  "ME-405": "https://career-shiksha.com/post/rgpv-previous-year-question-paper-me-405-manufacturing-technology-b-tech/", 
  "ME-501": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-501-internal-combustion-engines-b-tech/",
  "ME-502": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-502-mechanical-vibration-b-tech/",
  "ME-503-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-503b-dynamics-of-machine-dom-b-tech/",
  "ME-504-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-504a-industrial-engineering-and-ergonomics-b-tech/",
  "ME-504-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-504c-finite-element-method-fem-b-tech/",
  "ME-601": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-601-thermal-engineering-and-gas-dynamics-b-tech/",
  "ME-602": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-602-machine-component-design-b-tech/",
  "ME-603-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-603-a-turbo-machinery-b-tech/",
  "ME-603-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-603-c-product-design-b-tech/",
  "ME-604-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-604-b-optimization-techniques-b-tech/", 
  "ME-604-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-604-c-renewable-energy-technology-b-tech/",  
 
  "ME-701": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-701-heat-and-mass-transfer-b-tech/",
  "ME-702-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-702-a-advance-machining-processes-b-tech/",
  "ME-702-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-702-c-power-plant-engineering-b-tech/",
  "ME-703-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-703-a-operation-research-and-supply-b-tech/",

  "ME-801": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-801-refrigeration-and-air-conditioning-b-tech/",
  "ME-802-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-802-a-automobile-engineering-b-tech/",
  "ME-803-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-me-803-b-energy-conservation-management-and-audit-b-tech/",  

  // Civil Engineering CE
  
  "BT-301": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-bt-301-mathematics-iii-m-iii-b-tech/",
  "CE-302": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-302-construction-material-b-tech/",
  "CE-303": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-303-surveying-b-tech/",
  "CE-304": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-304-building-planning-and-architecture-b-tech/",
  "CE-305": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-305-strength-of-materials-b-tech/",
  "ES-401": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-es-401-energy-environmental-engineering-b-tech/",
  "CE-402": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-402-construction-technology-b-tech/",
  "CE-403": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-403-structural-analysis-i-b-tech/",
  "CE-404": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-404-transportation-engineering-i-b-tech/",
  "CE-405": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-405-engineering-geology-remote-sensing-b-tech/",
  "CE-501": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-501-fluid-mechanics-i-fm-i-fem-b-tech/,",
  "CE-502": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-502-transport-engineering-ii-te-ii-b-tech/,",
  "CE-503-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-503c-quantity-surveying-and-costing-b-tech/, ",
  "CE-503-D": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-503-d-marine-construction-b-tech/,",
  "CE-504-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-504-b-remote-sensing-and-gis-b-tech/,",
  "CE-504-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-504-c-renewable-energy-resources-b-tech/,",
  "CE-601": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-601-structural-design-and-drawing-rcc-i-b-tech/",
  "CE-602": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-602-environmental-engineering-i-b-tech/",
  "CE-603-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-603-a-water-resources-engineering-b-tech/",
  "CE-603-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-603-b-precast-and-modular-construction-b-tech/",
  "CE-603-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-603-c-advance-pavement-design-b-tech/,",
  "CE-604-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-604-c-environmental-impact-assessment-b-tech/,",
  "CE-701": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-701-geotechnical-engineering-b-tech/,",
  "CE-702-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-702-a-prestressed-concrete-structures-b-tech/,",
  "CE-702-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-702-b-environmental-engineering-ii-b-tech/",
  "CE-702-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-702-c-structural-dynamics-b-tech/",
  "CE-702-D": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-702-d-structural-design-and-drawing-rcc-ii-b-tech/",
  "CE-703-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-703-b-project-management-b-tech/",
  "CE-703-D": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-703-d-building-services-b-tech/",
  "CE-801": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-801-design-of-steel-structures-b-tech/",
  "CE-802-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-802-b-foundation-engineering-b-tech/",
  "CE-803-D": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ce-803-d-integrated-water-management-b-tech/",
  

  // Electrical and electronics Engineering EX
  "ES-301": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-es-301-energy-environment-engineering-b-tech/",
  "EX-302": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-302-signals-and-systems-b-tech/",
  "EX-303": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ec-303-digital-system-design-b-tech//",
  "EX-304": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-304-network-analysis-b-tech/",
  "EX-305": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-305-analog-electronics-b-tech/",

  "BT-401": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-bt-401-mathematics-iii-b-tech/",
  "EX-402": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-402-electrical-machine-i-b-tech/",
  "EX-403": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-403-digital-electronics-logic-design-deld-b-tech/",
  "EX-404": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-404-power-system-i-b-tech/,",
  "EX-405": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-405-control-system-b-tech/,",
  "EX-501": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-ee-501-electrical-machine-ii-b-tech/,",
  "EX-502": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-ee-502-power-electronics-b-tech/",
  "EX-503-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-503-a-electrical-power-generation-and-economy-b-tech/",
  "EX-503-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-503-c-renewable-power-generation-b-tech//",
  "EX-504-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-ee-504-a-industrial-electronics-b-tech/",
  "EX-504-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-504-b-electromagnetic-theory-b-tech//",
  "EX-504-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-504-c-electrical-and-electronics-materials-b-tech/",
  "EX-601": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-601-power-system-ii-b-tech/",
  "EX-602": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-602-microprocessor-and-microcontroller-b-tech/",
  "EX-603-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-603-b-energy-conservation-and-management-b-tech/",
  "EX-604-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-604-a-electronic-instrumentation-b-tech/",
  "EX-701": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-701-power-system-protection-b-tech/",
  "EX-702-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-702-a-power-electronics-application-to-power-system-b-tech/",
  "EX-703-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-703-b-energy-audit-management-b-tech/,",
  "EX-703-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-703-c-digital-signal-processing-b-tech/",
  "EX-801": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-801-electrical-drives-b-tech/",
  "EX-802-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-802-b-special-machine-b-tech/,",
  "EX-803-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-ex-803-a-power-electronics-converters-for-renewable-energy-b-tech/",

  // Computer Science & Information Technology
  "ES-301": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-es-301-energy-environment-engineering-b-tech/",
  "CSIT-302": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-csit-302-discrete-structure-b-tech/",
  "CSIT-303": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-csit-303-data-structures-b-tech/",
  "CSIT-304": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-csit-304-digital-systems-b-tech/",
  "CSIT-305": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-csit-305-object-oriented-programming-and-methodology-b-tech/",
  "BT-401": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-bt-401-mathematics-iii-b-tech/",
  "CSIT-404": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-csit-404-computer-organization-architecture-b-tech/",
 "CSIT-501": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-csit-501-computer-networking-b-tech/",
"CSIT-502": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-csit-502-operating-system-b-tech/",
"CSIT-503-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-csit-503a-theory-of-computation-b-tech/",
"CSIT-504-C": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-csit-504c-web-technology-e-commerce-b-tech/",

// Artificial Intelligence and Data Science
"AL-301": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-301-technical-communication-b-tech/",
"AL-302": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-302-introduction-to-probability-statistics-b-tech/",
"AL-303": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-303-data-structure-b-tech/",
"AL-304": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-304-artificial-intelligence-b-tech/",
"AL-305": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-305-oopm-b-tech/",
"AL-401": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-401-introduction-to-discrete-structure-and-linear-algebra-b-tech/,",
"AL-403": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-403-software-engineering-b-tech/",
"AL-404": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-404-computer-organization-architecture-b-tech/",
"AL-501": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-501-operating-system-b-tech/",
"AL-502": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-502-dbms-b-tech/",
"AL-503-B": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-503b-deep-learning-b-tech/",
"AL-504-A": "https://career-shiksha.com/post/rgpv-previous-old-year-question-paper-al-504a-ai-in-health-care-b-tech/",
  // 🔄 Add more as needed
};